resolver: lts-7.15

packages:
- '.'
- '../../../test/hslack'
# - slack-0.1.0.0
# - location:
#     git: https://github.com/supermario/helm.git
#     commit: f95c6c9

extra-deps:
- google-translate-0.3
- html-entities-1.1.2
- aeson-1.0.2.1
# - async-2.1.1

flags: {}
extra-package-dbs: []
